theme: minima
title: CodeWorks Journal
tagline: Learn to Code. Develop your future!
description: CodeWorks Fullstack student guide
author: CodeWorks
logo: /assets/img/codeworks.png
plugins:
  - jekyll-seo-tag